config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'users#index'
  resources 'users' do
    collection do
      get 'for_auth'
      get 'for_all'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, length: { minimum: 2, maximum: 100 }
  validates :family, presence: true, length: { minimum: 2, maximum: 100 }
  validates :phone, presence: true
end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  before_action :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # v.3.5 syntax. will be deprecated in 4.0
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) do |user_params|
      user_params.permit(:email, :password, :family, :name, :phone, :status, :remember_me)
    end

    devise_parameter_sanitizer.for(:sign_up) do |user_params|
      user_params.permit(:email, :password, :password_confirmation, :family, :name, :phone, :status)
    end

    devise_parameter_sanitizer.for(:account_update) do |user_params|
      user_params.permit(:email, :password, :current_password, :password_confirmation, :family, :name, :phone, :status)
    end
  end
  protected :configure_permitted_parameters

  def after_sign_in_path_for(_resource)
    if current_user&.status == 'inactive'
      reset_session
      users_path
    else
      for_auth_users_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :for_all, :destroy, :edit, :update]
  before_action :setup_user, only: [:edit, :update, :destroy]

  respond_to :html

  def index
    respond_with @users = User.all
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end

  private

    def setup_user
      @user = User.find params[:id]
    end

    def user_params
      params.require(:user).permit(:name, :email, :family, :status, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Arksys"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="."Arksys
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              li=link_to 'page for everybody', for_all_users_path
              li=link_to 'page for auth users', for_auth_users_path
              -if current_user
                li= link_to "#{current_user.name}", users_path
                li= link_to "Log out", destroy_user_session_path, :method => :delete
              -else
                li= link_to "Log in", new_user_session_path
                li= link_to "Sign up", new_user_registration_path

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            h3 Sidebar
            ul.nav.nav-list
              li.nav-header Sidebar
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

      footer
        p &copy; Company 2016

app/views/users/_user.html.slim
-@users.each do |user|
  tr
    td= link_to user.name, edit_user_path( user)
    td= link_to user.family, edit_user_path( user)
    td= link_to user.email, edit_user_path( user)
    td= user.status
    td=link_to 'Delete', user_path(user), method: :delete, class: 'btn btn-xs btn-danger'

app/views/users/edit.html.slim
.ppanel.panel-default
  .panel-body
    = form_for(@user) do |f|
      .form-group
        = f.label :Family
        = f.text_field :family, autofocus: true, class: "form-control"
      .form-group
        = f.label :Name
        = f.text_field :name, class: "form-control"
      .form-group
        = f.label :phone
        = f.phone_field :phone, class: "form-control"
      .form-group
        = f.label :email
        = f.email_field :email,  class: "form-control"
      .form-group
        = f.label :status
        = f.select(:status,['active','inactive'], {},  {class: "form-control"})
      = f.submit 'Update', class: "btn btn-primary"
= link_to t('.back', :default => 'Back'), :back

app/views/users/for_all.html.slim
Страница Тестовая страница для всех пользователей. Страница доступна без авторизации в приложении. Содержит любую произвольную информацию.

app/views/users/for_auth.html.slim
Страница Тестовая страница только для авторизованных пользователей. Страница доступна только авторизованным пользователям.

app/views/users/index.html.slim
table.table.table-condensed
  tr
    td Name
    td Family
    td email
    td status
    td actions
  =render 'user'